config/routes.rb
Trial::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

root 'users#index'
 resources :users
 resources :sessions
 resources :films do#, only: [:index, :show, :book]
  resources :shows
end

 get 'users/new' => 'users#new'
 post 'users/new' => 'users#create'
 get 'sessions/login' => 'sessions#show'
 post 'sessions/login' => 'sessions#login_attempt'
 post 'sessions/logout' => 'users#index'
 
match "/films/show/:film_id" => "films#show", :via => [:get], :as => "show"
get "films/:film_id/shows/new/:show_id" => 'shows#new'
post "films/:film_id/shows/new" => 'shows#create'
get "films/:film_id/shows/new" => 'shows#view'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base
end

app/models/film.rb
class Film < ActiveRecord::Base
	has_many :shows
	

#def show_timings_display
#	timing[]
#	vacancies[]
#	time=Show.find(params[:film_id])
#	while film_id!=film_id.last+1
#		if film_id==time.film_id
#			timing[]<<time.timing
#			vacancies[]<<time.vacancies
#		end
#	end
#end



end

app/models/show.rb
class Show < ActiveRecord::Base
	belongs_to :film
end

app/models/user.rb
class User < ActiveRecord::Base
	 attr_accessor :password

validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
validates :password, :confirmation => true #password_confirmation attr
validates_length_of :password, :in => 6..20, :on => :create

	before_save :encrypt_password
	after_save :clear_password

	def encrypt_password
		if password.present?
			self.salt= BCrypt::Engine.generate_salt
			self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
		end
	end

	def clear_password
		self.password=nil
	end

	def self.authenticate(name="", login_password="")
		user = User.find_by_name(name)
		
		if user && user.match_password(login_password)
			return user
		else
			return false
		end
	end

	def match_password(login_password="")
		encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected
	def authenticate_user
		if session[:user_id]
			@current_user=User.find session[:user_id]
			return true
		else
			redirect_to(:controller => 'sessions', :action =>'show')
			return false
		end
	end

	def save_login_state
		if session[:user_id]
			redirect_to :root
			return false
		else
			return true
		end
	end


end

app/controllers/films_controller.rb
class FilmsController < ApplicationController


	def index
		@filmdisplay=Film.all

	end

	def show
		@film=Show.find(params[:film_id])
		@title=Film.find(params[:film_id])
	end
	def new
		
	end

	def create
		
	end

	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def login
end

def show
	end

def login_attempt
		authorized_user = User.authenticate(params[:name],params[:login_password])
			if authorized_user
				session[:user_id] = authorized_user.id
				flash[:notice] = "Welcome, you are now logged in as #{authorized_user.name}"
				redirect_to films_path
			else
				flash[:notice] = "Invalid Username or Password"
				render "show"
			end
end


def logout
	session[:user_id] = nil
	redirect_to :root
end

def home
	@current_user=User.all
	
end

before_filter :authenticate_user, :only => [:home]
before_filter :save_login_state, :only => [:login, :login_attempt]

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

def new
	    @book=Booking.new
		@film=Film.find(params[:film_id])
		@show=Show.find(params[:id])
end
def create
	@book=Booking.new(booking_params)
		if @book.save
			flash[:now]= "Created!"
			render 'view'
		else
			render 'new'
		end
end
def view
 @book=Booking.find(params[:booking_id])
 @film=Film.find(params[:film_id])
 @show=Show.find(params[:show_id])
end


private
	def booking_params
		params.require(:booking).permit(:seats, :user_id, :show_id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user=User.new
	end

	def index
	end

	def create
		@user=User.new(user_params)
		if @user.save
			flash[:now]= "Created!"
			redirect_to sessions_login_path
		else
			render 'new'
		end
	end

	before_filter :save_login_state, :only => [:new, :create]
    def show
    end
	private
	def user_params
		params.require(:user).permit(:name, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/films/book.html.erb
<h1> BOOKINGS FOR THE MOVIE <strong><%= @film.name %></strong></h1>
<div class="booking">
<%= form_for :booking do |b| %>
<%= b.label :Enter_the_number_of_seats_you_want %>
<%= b.text_field :seats %>
<%= b.submit %>
<% end %>
<%= @view.id %>

</div>

app/views/films/create.html.erb
Films Create

app/views/films/index.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
			<div class="navbar-header">
				<div class="container pull-left">
					<nav>
				<a class="navbar-brand pull-left" href="#">
						<li><%= link_to "Home", users_path %></li>
						<li><%= link_to "Log Out", sessions_logout_path %></li>
				</a>
			        </nav>
				</div>
			</div>
</nav>




<div class="movieflash">
	<%= flash[:notice] %>
</div>
<h1> Movie List </h1>
<table class="table table-striped table-bordered table-condensed">
	<tr>
		<td><strong>Movie </strong></td>
		<td><strong> Rating </strong></td>
	</tr>
<% @filmdisplay.each do |film| %>
	<tr>
		<td><%= link_to film.name , show_path(film) %></td>
		<td><%= film.rating %></td>
	</tr>
	
<% end %>
</table>

app/views/films/show.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
			<div class="navbar-header">
				<div class="container pull-left">
					<nav>
				<a class="navbar-brand pull-left" href="#">
						<li><%= link_to "Home", users_path %></li>
						<li><%= link_to "Log Out", sessions_logout_path %></li>
						<li><%= link_to "Back to Movie List", films_path %></li>
				</a>
			        </nav>
				</div>
			</div>
</nav>


<h3> Show Timings for <strong><%= @title.name %> </strong>: </h3>

<table class="table table-striped table-bordered table-condensed">
	<tr>
		<th> Timings </th>
		<th> Vacancies </th>
	</tr>

	<% Show.all.each do |a| %>
	<% if a.film_id==@title.id %>
	<tr>
		<td><%= link_to a.timing, :controller =>"shows", :action => "new", :id => a %></td>
		<td><%= a.vacancies %></td>
	</tr>
<% end %>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>

  <title>Trial</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	
<%= yield %>

</body>
</html>

app/views/shows/new.html.erb
<div class="select"> BOOKINGS FOR THE MOVIE <strong><%= @film.name %> </strong> for <%= @show.timing %> show </div>
<div class="booking">
<%= form_for :booking, :html => {:class=> "Forms"} do |b| %>
<%= b.label :Enter_the_number_of_seats_you_want %>
<%= b.text_field :seats %></br>
<%= b.hidden_field :film_id %>
<%= b.hidden_field :show_id %>
</br><%= b.submit %>
<% end %>

</div>

app/views/shows/view.html.erb
<%= @book.film_id %>
<%= @book.seats %>



<%= @book.show_id %>

app/views/users/_logging.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
			<div class="navbar-header">
				<div class="container">
					<nav>
				<a class="navbar-brand" href="#">
					
					    <li><%= link_to "Home", users_path %></li>
						<li><%= link_to "Sign In", sessions_login_path %></li>
						<li><%= link_to "Sign Up", users_new_path %></li>
				</a>
			        </nav>
				</div>
			</div>
</nav>

app/views/users/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<%= render "logging" %>
<div class="center hero-unit">
	<h1> Sign in or sign up to book tickets for your favourite movies!</h1>
</div>

app/views/users/new.html.erb
<div class="Sign_Form">
	<nav class="navbar navbar-default navbar-inverse" role="navigation">
			<div class="navbar-header">
				<div class="container">
					<nav>
				<a class="navbar-brand" href="#">
						<li><%= link_to "Home", users_path %></li>
						<li><%= link_to "Sign In", sessions_login_path %></li>
						
				</a>
			        </nav>
				</div>
			</div>
</nav>

<h1>Sign Up</h1>
<%= form_for :user, :url => {:controller => 'users', :action => 'create'}, :html => {:class=> "Forms"} do |f| %>
<p> Username:</br> <%= f.text_field :name %> </p>
<p> Password:</br> <%= f.password_field :password%></p>
<p>Password Confirmation:</br> <%= f.password_field :password_confirmation %></p></br>
<%= submit_tag("Sign Up") %>
<% end %>

<% if @user.errors.any? %>
<div class="Signup_Errors">
<% for message_error in @user.errors.full_messages %>
<li><%= message_error %></li></br>
<% end %>
</div>
<% end %>
</div>

app/views/users/show.html.erb
<h2>hey u r in users</h2>